# Generated by Django 5.0.7 on 2024-08-02 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocomment', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choose.comment')),
            ],
        ),
    ]
